import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import CursorGlow from "./components/CursorGlow";
import Footer from "./components/footer";




export const metadata: Metadata = {
  title: "photography",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={` antialiased`}
    >
      <body className=""> <CursorGlow />{children}
      <Footer />
      </body>
    </html>
  );
}
